// todo-app-sveltejs/src/components/ToDoItem.svelte
<script>
    export let id;
    export let text;
    export let deleteItem;
</script>

<div class="todo-item">
    <p>{text} <small>[id:{id}]</small></p>
    
    <button class="todo-item-delete" on:click={() => deleteItem(id)}>-</button>
</div>

<style>  
    .todo-item {
        display: flex;
        justify-content: center;
        align-items: center;
    }
    p {
        width: 90%;
        background-color: white;
        border: 1px solid lightgrey;
        box-shadow: 1px 1px 1px lightgrey;
        padding: 12px;
        margin: 10px;
    }
    p small {
        color: #666;
        font-size: small;
    }
    .todo-item-delete {
        padding: 4px 12px;
        margin: 10px;
        margin-left: 0;
        cursor: pointer;
        background: #ff7373;
        border-radius: 10px;
        box-shadow: 1px 1px 1px #c70202;
        color: white;
        font-size: 28px;
        width: 1.7em;
    }
    .todo-item-delete:hover {
        box-shadow: none;
    }
</style>

// todo-app-vuejs/src/components/ToDoItem.vue
<template>
  <div class="ToDoItem">
    <p class="ToDoItem-Text">{{item.text}} <small>[id:{{item.id}}]</small></p>
    <button class="ToDoItem-Delete" @click="deleteItem(item.id)">-</button>
  </div>
</template>

<script>
export default {
  name: "ToDoItem",
  props: ["item"],
  methods: {
    deleteItem(id) {
      this.$emit("delete", id);
    }
  }
};
</script>

<style>
    .ToDoItem {
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .ToDoItem-Text {
        width: 90%;
        background-color: white;
        border: 1px solid lightgrey;
        box-shadow: 1px 1px 1px lightgrey;
        padding: 12px;
        margin: 10px;
    }
    .ToDoItem-Text small {
        color: #666;
        font-size: small;
    }
    .ToDoItem-Delete {
        padding: 4px 12px;
        margin: 10px;
        margin-left: 0;
        cursor: pointer;
        background: #ff7373;
        border-radius: 10px;
        box-shadow: 1px 1px 1px #c70202;
        color: white;
        font-size: 28px;
        width: 1.7em;
    }
    .ToDoItem-Delete:hover {
        box-shadow: none;
    }
</style>
